rabbit:
  main:
    username: "user"
    password: "root"
    host: "rabbitmq.loc"
    port: 5672
  services:
    kazarma:
      exchange: "amq.topic"
      queue: "client_actions_queue"
      routing_key: "client.actions.*"

proxies:
  balance_add:
    enabled: true
  new_user:
    enabled: true
